---
- id: '1654001290028'
  alias: Wake-up light alarm main-bedroom
  description: ''
  use_blueprint:
    path: sbyx/wake-up-light-alarm-with-sunrise-effect.yaml
    input:
      manual_time: 05:40:00
      light_entity: light.main_bedroom
      check_entity: binary_sensor.workday_sensor
      start_brightness: 30
      end_brightness: 90
      pre_sunrise_actions:
        - service: switch.turn_off
          data: {}
          target:
            entity_id: switch.adaptive_lighting_sleep_mode_main_bedroom
        - service: timer.start
          data: {}
          target:
            entity_id: timer.morning_wakup_window
