light:
  - platform: group
    name: Lights whole night
    entities:
      - light.outside_kitchen
  - platform: group
    name: Lights while awake
    entities:
      - light.courtyard_braai
      - light.courtyard_lounge
      - light.courtyard_main_bedroom
      #- light.pool_light

automation:
  ## Whole night
  - alias: "Turn on outside lights and check every minute - whole night"
    trigger:
      - platform: time_pattern
        # You can also match on interval. This will match every x minutes
        minutes: "/1"
    condition:
      condition: or
      conditions:
        - condition: sun
          after: sunset
          #after_offset: "00:20:00"
        - condition: sun
          before: sunrise
          #before_offset: "-00:20:00"
    action:
      - service: light.turn_on
        entity_id: 
          - light.lights_whole_night
  ## Whole day
  - alias: "Turn off outside lights and check every minute - whole night"
    trigger:
      - platform: time_pattern
        # You can also match on interval. This will match every x minutes
        minutes: "/1"
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunrise
          #after_offset: "-00:20:00"
        - condition: sun
          before: sunset
          #before_offset: "00:20:00"
    action:
      - service: light.turn_off
        entity_id: 
          - light.lights_whole_night
  
  ## While awake
  - alias: "Turn on outside lights and check every minute - whole awake"
    trigger:
      - platform: time_pattern
        # You can also match on interval. This will match every x minutes
        minutes: "/1"
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: disarmed
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            #after_offset: "00:20:00"
          - condition: sun
            before: sunrise
            #before_offset: "-00:20:00"
    action:
      - service: light.turn_on
        data_template:
          entity_id: >
            light.lights_while_awake
            {% if is_state('input_boolean.pool_cover_on','off') %},{{ " " }}light.pool_light{% endif -%}
  ## While not awake
  - alias: "Turn off outside lights and check every minute - whole not awake"
    trigger:
      - platform: time_pattern
        # You can also match on interval. This will match every x minutes
        minutes: "/1"
    condition:
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: sun
                after: sunrise
                #after_offset: "-00:20:00"
              - condition: sun
                before: sunset
                #before_offset: "00:20:00"
          - condition: state
            entity_id: alarm_control_panel.home_alarm
            state: armed_home
          - condition: state
            entity_id: alarm_control_panel.home_alarm
            state: armed_night
          - condition: state
            entity_id: alarm_control_panel.home_alarm
            state: armed_away
    action:
      - service: light.turn_off
        entity_id: 
          - light.lights_while_awake
          - light.pool_light
