automation:
  # AC-Office PM
  - alias: Turn off office AC end of work day
    trigger:
      # If office AC is on at 5:30 turn off 
      - platform: template
        value_template: >
          {{ (now().time().strftime("%R") == "17:30" and states('climate.midea_ac_32985348871179') != "off") }}
    action:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.midea_ac_32985348871179
        data:
          hvac_mode: fan_only

  # AC-Bedrooms AM
  - alias: Turn off bedroom ACs in the AM
    trigger:
      - platform: time
        at: '5:30:00'
    action:
      - service: script.ac_mainbedroom_off
      - service: script.ac_childbedroom_off

script:
  # AC-MainBed AM
  ac_mainbedroom_off:
    sequence:
      - condition: template
        value_template: >
          {{ (states('climate.midea_ac_30786325862093') != "off") }}
      - service: climate.turn_off
        target:
          entity_id: climate.midea_ac_30786325862093

  # AC-childBed AM
  ac_childbedroom_off:
    sequence:
      - condition: template
        value_template: >
          {{ (states('climate.midea_ac_30786325862153') != "off") }}
      - service: climate.turn_off
        target:
          entity_id: climate.midea_ac_30786325862153
