---
#-
#
#  ___  ___ _ __  ___  ___  _ __ ___
# / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
# \__ \  __/ | | \__ \ (_) | |  \__ \
# |___/\___|_| |_|___/\___/|_|  |___/
#
#
#- from github.com/tinuva/home-assistant-config

#  _____                    _       _
# |_   _|__ _ __ ___  _ __ | | __ _| |_ ___    ___  ___ _ __  ___  ___  _ __ ___
#   | |/ _ \ '_ ` _ \| '_ \| |/ _` | __/ _ \  / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
#   | |  __/ | | | | | |_) | | (_| | ||  __/  \__ \  __/ | | \__ \ (_) | |  \__ \
#   |_|\___|_| |_| |_| .__/|_|\__,_|\__\___|  |___/\___|_| |_|___/\___/|_|  |___/
#                    |_|

#### Sureflap Jessie
#- platform: history_stats
#  name: Jessie outside time (today)
#  entity_id: binary_sensor.pet_jessie
#  state: 'off'
#  type: time
#  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
#  end: '{{ now() }}'
#- platform: history_stats
#  name: Jessie trips outside (today)
#  entity_id: binary_sensor.pet_jessie
#  state: 'off'
#  type: count
#  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
#  end: '{{ now() }}'
#- platform: history_stats
#  name: Jessie outside (yesterday)
#  entity_id: binary_sensor.pet_jessie
#  state: 'off'
#  type: time
#  end : '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
#  duration:
#    hours: 24
#- platform: history_stats
#  name: Jessie trips outside (yesterday)
#  entity_id: binary_sensor.pet_jessie
#  state: 'off'
#  type: count
#  end : '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
#  duration:
#    hours: 24
#### Sureflap Ziva
#- platform: history_stats
#  name: Ziva outside time (today)
#  entity_id: binary_sensor.pet_ziva
#  state: 'off'
#  type: time
#  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
#  end: '{{ now() }}'
#- platform: history_stats
#  name: Ziva trips outside (today)
#  entity_id: binary_sensor.pet_ziva
#  state: 'off'
#  type: count
#  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
#  end: '{{ now() }}'
#- platform: history_stats
#  name: Ziva outside (yesterday)
#  entity_id: binary_sensor.pet_ziva
#  state: 'off'
#  type: time
#  end : '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
#  duration:
#    hours: 24
#- platform: history_stats
#  name: Ziva trips outside (yesterday)
#  entity_id: binary_sensor.pet_ziva
#  state: 'off'
#  type: count
#  end : '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
#  duration:
#    hours: 24
#### Sureflap end

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'

- platform: template
  sensors:
    dayoftheweek:
      value_template: "{{ ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][now().weekday()] }}"

- platform: template
  sensors:
    month:
      value_template: "{{ ['January','February','March','April','May','June','July','August','September','October','November','December'][now().month-1] }}"

- platform: template
  sensors:
    dayofthemonth:
      value_template: "{{ ['1st','2nd','3rd','4th','5th','6th','7th','8th','9th','10th','11th','12th','13th','14th','15th','16th','17th','18th','19th','20th','21th','22th','23th','24th','25th','26th','27th','28th','29th','30th','31th' ][ now().day-1] }}"

#- platform: command_line
#  name: "Virgin Active - Tygervalley"
#  #command: 'curl -H "Authorization: xxx" -H "Content-Type : application/json" https://selfaccess.virginactive.co.za/Api/occupancy/club/#Tygervalley'
#  command: !secret va_url_tygervalley
#  value_template: 'value'
#  json_attributes:
#    - active
#    - maxLimit
#    - occupancy
#  scan_interval: 300
#
#- platform: command_line
#  name: "Virgin Active - Durbanville"
#  #command: 'curl -H "Authorization: xxx" -H "Content-Type : application/json" https://selfaccess.virginactive.co.za/Api/occupancy/club/#Durbanville'
#  command: !secret va_url_durbanville
#  value_template: 'value'
#  json_attributes:
#    - active
#    - maxLimit
#    - occupancy
#  scan_interval: 300

#- platform: template
#  sensors:
#    virgin_active_tygervalley_occupancy:
#      value_template: "{{ state_attr('sensor.virgin_active_tygervalley', 'active')|int / state_attr('sensor.virgin_active_tygervalley', #'maxLimit')|int * 100}}"
#      friendly_name: "Virgin Active - Tygervalley Occupancy"
#      unit_of_measurement: '%'
#- platform: template
#  sensors:
#    virgin_active_durbanville_occupancy:
#      value_template: "{{ state_attr('sensor.virgin_active_durbanville', 'active')|int / state_attr('sensor.virgin_active_durbanville', #'maxLimit')|int * 100}}"
#      friendly_name: "Virgin Active - Durbanville Occupancy"
#      unit_of_measurement: '%'
