logbook:
  exclude:
    entities:
      - sensor.octoprint_last_event
history:
  exclude:
    entities:
      - sensor.octoprint_last_event

automation:
  - alias: 3dprint stopped
    trigger:
      - platform: state
        entity_id: binary_sensor.octoprint_printing
        from: 'on'
        to: 'off'
      - platform: state
        entity_id: binary_sensor.octoprint_printing_2
        from: 'on'
        to: 'off'
    action:
      - service: script.log
        data:
          target: 'alerts-david'
          icon: ':printer:'
          object: '3D Printer'
          message: >
            Printing stopped @ progress: {{ states('sensor.octoprint_print_progress') }} Time: {{ states('sensor.octoprint_print_time') }}
            File: {{ states('sensor.octoprint_print_file') }}

  - alias: 3dprint temp changed
    trigger:
      - platform: state
        entity_id: sensor.octoprint_bed_target
      - platform: state
        entity_id: sensor.octoprint_tool_0_target
    condition:
      - condition: or
        conditions:
        - condition: state
          entity_id: switch.octoprint_printing
          state: 'on'
        - condition: state
          entity_id: switch.octoprint_printing_2
          state: 'on'
    action:
      - service: script.log
        data:
          target: 'alerts-david'
          icon: ':printer:'
          object: '3D Printer'
          message: >
            Printing target temperatures changed @ progress: {{ states('sensor.octoprint_print_progress') }} Time: {{ states('sensor.octoprint_print_time') }} Left: {{ states('sensor.octoprint_print_time_left') }}
            File: {{ states('sensor.octoprint_print_file') }}
            Bed Target: {{ states('sensor.octoprint_bed_target') }}
            Hotend Target: {{ states('sensor.octoprint_tool_0_target') }}