camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: https://octo.heaven.za.net/webcam/?action=snapshot
    mjpeg_url: https://octo.heaven.za.net/webcam/?action=stream

logbook:
  exclude:
    entities:
      - sensor.octoprint_last_event
history:
  exclude:
    entities:
      - sensor.octoprint_last_event

automation:
  - alias: 3dprint stopped
    trigger:
      - platform: state
        entity_id: binary_sensor.octoprint_printing
        from: 'on'
        to: 'off'
    condition:
      - condition: numeric_state
        entity_id: sensor.octoprint_print_progress
        above: '0'
    action:
      - service: script.alert
        data:
          target: 'alerts-david'
          icon: ':printer:'
          object: '3D Printer'
          camera: 'camera.octoprint'
          message: >
            Printing stopped @ progress: {{ states('sensor.octoprint_print_progress') | int }} {{- '\n' -}}
            Time: {{ states('sensor.octoprint_print_time') }} {{- '\n' -}}
            File: {{ states('sensor.octoprint_print_file') }}

  - alias: 3dprint temp changed
    trigger:
      - platform: state
        entity_id: sensor.octoprint_bed_target
      - platform: state
        entity_id: sensor.octoprint_tool_0_target
    condition:
      - condition: or
        conditions:
        - condition: state
          entity_id: switch.octoprint_printing
          state: 'on'
    action:
      - service: script.alert
        data:
          target: 'alerts-david'
          icon: ':printer:'
          object: '3D Printer'
          message: >
            Printing target temperatures changed @ progress: {{ states('sensor.octoprint_print_progress') | int }} {{- '\n' -}}
            Time: {{ states('sensor.octoprint_print_time') }} Left: {{ states('sensor.octoprint_print_time_left') }} {{- '\n' -}}
            File: {{ states('sensor.octoprint_print_file') }} {{- '\n' -}}
            Bed Target: {{ states('sensor.octoprint_bed_target') }} {{- '\n' -}}
            Hotend Target: {{ states('sensor.octoprint_tool_0_target') }}