automation:
  - alias: Bypass zone with burglar bars
    trigger:
      - entity_id: binary_sensor.main_bedroom_window
        platform: state
        to: 'on'
      - entity_id: alarm_control_panel.home_alarm
        platform: state
        to: 'disarmed'
      - entity_id: sensor.home_alarm_keypad
        platform: state
        to: 'Not Ready'
    condition:
      - condition: state
        entity_id: switch.main_bedroom_window_bypass
        state: 'off'
    action:
      - service: script.log
        data:
          icon: ':rotating_light:'
          object: 'Home Alarm'
          message: >
            Setting alarm bypass on main bed room window
      - service: switch.turn_on
        data:
          entity_id: switch.main_bedroom_window_bypass