sensor:
  - platform: goodwe
    ip_address: 192.168.241.143
    #port: 8899
    #network_timeout: 2
    #network_retries: 3
    #scan_interval: 30
    #sensor_name_prefix: GoodWe

  - platform: template
    sensors:
      # Template sensor for values of energy bought (active_power < 0)
      energy_buy:
        friendly_name: "GoodWe Grid Power"
        unit_of_measurement: 'W'
        icon_template: "mdi:flash"
        value_template: >-
          {% if states('sensor.goodwe_pgrid')|float < 0 %}
            {{ (states('sensor.goodwe_pgrid')|float * -1)|round(0) }}
          {% else %}
            {{ 0 }}
          {% endif %}
      # Template sensor for values of energy sold (active_power > 0)
      energy_sell:
        friendly_name: "Energy Sell"
        unit_of_measurement: 'W'
        icon_template: "mdi:flash"
        value_template: >-
          {% if states('sensor.goodwe_pgrid')|float > 0 %}
            {{ states('sensor.goodwe_pgrid')|float }}
          {% else %}
            {{ 0 }}
          {% endif %}
      # Template sensor for values of non-essential energy usage
      energy_non_essentials:
        friendly_name: "non-essentials Power"
        unit_of_measurement: 'W'
        icon_template: "mdi:flash"
        value_template: >-
          {% if (states('sensor.goodwe_house_consumption')|float - states('sensor.goodwe_pback_up')|float) > 0 %}
            {{ (states('sensor.goodwe_house_consumption')|float - states('sensor.goodwe_pback_up')|float)|round(0) }}
          {% else %}
            {{ 0 }}
          {% endif %}

  # Sensor for Riemann sum of energy bought (W -> Wh)
  - platform: integration
    source: sensor.energy_buy
    name: energy_buy_sum
    unit_prefix: k
    round: 1
    method: left
  # Sensor for Riemann sum of energy sold (W -> Wh)
  - platform: integration
    source: sensor.energy_sell
    name: energy_sell_sum
    unit_prefix: k
    round: 1
    method: left

  # Sensor for Riemann sum of solar energy generate (W -> Wh)
  - platform: integration
    source: sensor.goodwe_ppv
    name: energy_solar_generate
    unit_prefix: k
    round: 1
    method: left


  - platform: template
    sensors:
      # Template sensor for money used
      energy_buy_daily_cost:
        friendly_name: "energy_buy_daily_cost"
        icon_template: "mdi:flash"
        value_template: >-
          {% if states('sensor.energy_buy_monthly')|float > 600 %}
            {{ (states('sensor.energy_buy_daily')|float * 291.90 / 100)|round(2) }}
          {% else %}
            {{ (states('sensor.energy_buy_daily')|float * 211.52 / 100)|round(2) }}
          {% endif %}
      energy_buy_monthly_cost:
        friendly_name: "energy_buy_monthly_cost"
        icon_template: "mdi:flash"
        value_template: >-
          {% if states('sensor.energy_buy_monthly')|float > 600 %}
            {{ (((states('sensor.energy_buy_monthly')|float - 600) * 291.90 / 100)|round(2) + (600 * 211.52 / 100))|round(2) }}
          {% else %}
            {{ (states('sensor.energy_buy_monthly')|float * 211.52 / 100)|round(2) }}
          {% endif %}
      energy_generate_daily_saving:
        friendly_name: "energy_generate_daily_saving"
        icon_template: "mdi:flash"
        value_template: >-
          {% if states('sensor.energy_buy_monthly')|float > 600 %}
            {{ (states('sensor.solar_generate_daily')|float * 291.90 / 100)|round(2) }}
          {% else %}
            {{ (states('sensor.solar_generate_daily')|float * 211.52 / 100)|round(2) }}
          {% endif %}
      energy_generate_monthly_saving:
        friendly_name: "energy_generate_monthly_saving"
        icon_template: "mdi:flash"
        value_template: >-
          {{ (states('sensor.solar_generate_monthly')|float * 211.52 / 100)|round(2) }}

      grid_mode:
        friendly_name_template: "Grid Mode"
        value_template: >
          {% if states('sensor.goodwe_grid_mode') in ['unavailable','unknown','none'] -%}
            {{ states('sensor.grid_mode') }}
          {% else %}
            {{ states('sensor.goodwe_grid_mode') | int }}
          {% endif %}

utility_meter:
  energy_buy_daily:
    source: sensor.energy_buy_sum
    cycle: daily
  energy_buy_monthly:
    source: sensor.energy_buy_sum
    cycle: monthly
  energy_sell_daily:
    source: sensor.energy_sell_sum
    cycle: daily
  energy_sell_monthly:
    source: sensor.energy_sell_sum
    cycle: monthly
  house_consumption_daily:
    source: sensor.goodwe_house_consumption
    cycle: daily
  house_consumption_monthly:
    source: sensor.goodwe_house_consumption
    cycle: monthly
  solar_generate_daily:
    source: sensor.energy_solar_generate
    cycle: daily
  solar_generate_monthly:
    source: sensor.energy_solar_generate
    cycle: monthly

automation:
  # Notification - grid power lost
  - alias: notification - grid power lost
    trigger:
      - platform: state
        entity_id: sensor.grid_mode
        to: '0'
    condition:
      >
        {{ trigger.from_state is not none and
          trigger.from_state.state not in ['unknown','unavailable'] }}
    action:
      - service: notify.slack
        data_template:
          data:
            icon: ":zap:"
            username: "GoodWe"
            blocks_template:
              - type: section
                text:
                  type: mrkdwn
                  text: >
                    Eskom/Grid power lost
          title: 'Power'
          target: ["#alerts"]
          message: >
            Eskom/Grid power lost
  # Notification - grid power returned
  - alias: notification - grid power returned
    trigger:
      - platform: state
        entity_id: sensor.grid_mode
        to: '1'
    condition:
      >
        {{ trigger.from_state is not none and
          trigger.from_state.state not in ['unknown','unavailable'] }}
    action:
      - service: notify.slack
        data_template:
          data:
            icon: ":zap:"
            username: "GoodWe Robot"
            blocks_template:
              - type: section
                text:
                  type: mrkdwn
                  text: >
                    Eskom/Grid power returned
          title: 'Power'
          target: ["#alerts"]
          message: >
            Eskom/Grid power returned

  # notification daily kWh usage
  - alias: notification daily kWh usage
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == ( '86399' | int | timestamp_custom('%H:%M', False)) }}"
    action:
      - service: notify.slack
        data_template:
          data:
            icon: ":zap:"
            username: "GoodWe Robot"
            blocks_template:
              - type: header
                text:
                  type: plain_text
                  text: >
                    Power Usage Daily
              - type: section
                fields:
                  - type: mrkdwn
                    text: >
                      *Eskom:*
                      {{- '\n' -}}*Solar:*
                      {{- '\n' -}}*Total:*
                  - type: mrkdwn
                    text: >
                      {{ states('sensor.energy_buy_daily') }} kWh / R{{ states('sensor.energy_buy_daily_cost') }}
                      {{- '\n' -}}{{ states('sensor.solar_generate_daily') }} kWh / R{{ states('sensor.energy_generate_daily_saving') }}
                      {{- '\n' -}}{{ states('sensor.energy_buy_daily')|float + states('sensor.solar_generate_daily')|float }} kWh / R{{ states('sensor.energy_buy_daily_cost')|float + states('sensor.energy_generate_daily_saving')|float }}
              - type: header
                text:
                  type: plain_text
                  text: >
                    Power Usage Monthly
              - type: section
                fields:
                  - type: mrkdwn
                    text: >
                      *Eskom:*
                      {{- '\n' -}}*Solar:*
                      {{- '\n' -}}*Total:*
                  - type: mrkdwn
                    text: >
                      {{ states('sensor.energy_buy_monthly') }} kWh / R{{ states('sensor.energy_buy_monthly_cost') }}
                      {{- '\n' -}}{{ states('sensor.solar_generate_monthly') }} kWh / R{{ states('sensor.energy_generate_monthly_saving') }}
                      {{- '\n' -}}{{ states('sensor.energy_buy_monthly')|float + states('sensor.solar_generate_monthly')|float | int }} kWh / R{{ states('sensor.energy_buy_monthly_cost')|float + states('sensor.energy_generate_monthly_saving')|float }}
              - type: header
                text:
                  type: mrkdwn
                  text: >
                    <https://grafana.heaven.za.net/d/aVNSpZGGz/power-usage-goodwe?orgId=1&refresh=30s|View graphs>
          title: 'Power'
          target: ["#general"]
          message: >
            Today's power usage: {{ states('sensor.energy_buy_daily') }} kWh / R{{ states('sensor.energy_buy_daily_cost') }}
                    {{- '\n' -}}Today's solar generation: {{ states('sensor.solar_generate_daily') }} kWh / R{{ states('sensor.energy_generate_daily_saving') }}
                    {{- '\n' -}}This month's current usage: {{ states('sensor.energy_buy_monthly') }} kWh / R{{ states('sensor.energy_buy_monthly_cost') }}
                    {{- '\n' -}}This month's solar generation: {{ states('sensor.solar_generate_monthly') }} kWh / R{{ states('sensor.energy_generate_monthly_saving') }}
                    {{- '\n' -}}Total monthly usage: {{ states('sensor.energy_buy_monthly')|float + states('sensor.solar_generate_monthly')|float | int }} kWh / R{{ states('sensor.energy_buy_monthly_cost')|float + states('sensor.energy_generate_monthly_saving')|float }}

  ## notification if SoH drop below 50%
  - alias: Notify SoH below 50
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.goodwe_battery_soh
        below: '50'
    condition: []
    action:
      - service: notify.slack
        data_template:
          data:
            icon: ":zap:"
            username: "GoodWe Robot"
            blocks_template:
              - type: section
                text:
                  type: mrkdwn
                  text: >
                    GoodWe Battery State of Health LOW 
                    Current SoH: {{ states('sensor.goodwe_battery_soh') }}
          title: 'Power'
          target: ["#alerts"]
          message: >
            GoodWe Battery State of Health LOW 
            Current SoH: {{ states('sensor.goodwe_battery_soh') }}