automation:
  - alias: "Turn off main bathroom lights if on for x min"
    trigger:
      - platform: state
        entity_id: light.main_bathroom
        to: 'on'
        for:
          minutes: 20
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.main_bathroom