---
# sensor.eskom_loadshedding_stage provided by https://github.com/swartjean/ha-eskom-loadshedding

# Inputs managed by node-red
input_number:
  loadshedding_stage_eskom:
    name: Eskom Loadshedding Stage
    min: -100
    max: 8
  loadshedding_stage_coct:
    name: CoCT Loadshedding Stage
    min: -100
    max: 8

input_boolean:
  loadshedding_slot_active:
    name: Loadshedding slot active

timer:
  loadshedding_slot:
    duration: '02:35:00'

automation:
  - alias: start_loadshedding_slot_timer
    trigger:
      - platform: state
        entity_id: input_boolean.loadshedding_slot_active
        to: 'on'
      - platform: numeric_state
        entity_id: sensor.eskom_loadshedding_stage
        above: 0
    condition:
      # make sure timer not already active
      - condition: state
        entity_id: timer.loadshedding_slot
        state: 'idle'
      # check conditions for both tiggers
      - condition: state
        entity_id: input_boolean.loadshedding_slot_active
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.eskom_loadshedding_stage
        above: 0
    action:
      - service: timer.start
        data:
          entity_id: timer.loadshedding_slot
          duration: '02:30:00'
