sensor:
  - platform: seventeentrack
    username: !secret seventeentrack_user
    password: !secret seventeentrack_pass
  #- platform: aftership
  #  api_key: !secret aftership_api_key

automation:
  - alias: "Seventeentrack Update"
    initial_state: on
    trigger:
      platform: event
      event_type: state_changed
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ trigger.event.data.entity_id.startswith('sensor.seventeentrack_package_') }}"
        - condition: or
          conditions:
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ trigger.event.data.new_state.attributes.location != None }}"
              - condition: template
                value_template: "{{ trigger.event.data.new_state.attributes.location|trim != '' }}"
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ trigger.event.data.new_state.attributes.info_text != None }}"
              - condition: template
                value_template: "{{ trigger.event.data.new_state.attributes.info_text|trim != '' }}"
        #  - condition: template
        #    value_template: "{{ 'out for delivery' in trigger.event.data.new_state.attributes.info_text|lower }}"
        #  - condition: template
        #    value_template: "{{ 'delivered' in trigger.event.data.new_state.attributes.info_text|lower }}"
        #  - condition: template
        #    value_template: "{{ 'onboard' in trigger.event.data.new_state.attributes.info_text|lower }}"
    action:
      - service: notify.slack
        data_template:
          target: ["#alerts-david"]
          message: >
            Name: {{ trigger.event.data.new_state.attributes.tracking_number}} {{ trigger.event.data.new_state.attributes.friendly_name | replace("Seventeentrack Package: ","") }}
            {% if trigger.event.data.new_state.attributes.location != None %}
            {% if trigger.event.data.new_state.attributes.location|trim != '' %}
            {{- '\n' -}}Location: {{ trigger.event.data.new_state.attributes.location }}
            {% endif %}
            {% endif %}
            {% if trigger.event.data.new_state.attributes.info_text != None %}
            {% if trigger.event.data.new_state.attributes.info_text|trim != '' %}
            {{- '\n' -}}Event: {{ trigger.event.data.new_state.attributes.info_text }}
            {% endif %}
            {% endif %}
          data:
            icon: ":envelope:"
            username: "17track mail"
            blocks_template:
              - type: section
                text:
                  type: mrkdwn
                  text: >
                    Name: {{ trigger.event.data.new_state.attributes.tracking_number}} {{ trigger.event.data.new_state.attributes.friendly_name | replace("Seventeentrack Package: ","") }}
                    {% if trigger.event.data.new_state.attributes.location != None %}
                    {% if trigger.event.data.new_state.attributes.location|trim != '' %}
                    {{- '\n' -}}Location: {{ trigger.event.data.new_state.attributes.location }}
                    {% endif %}
                    {% endif %}
                    {% if trigger.event.data.new_state.attributes.info_text != None %}
                    {% if trigger.event.data.new_state.attributes.info_text|trim != '' %}
                    {{- '\n' -}}Event: {{ trigger.event.data.new_state.attributes.info_text }}
                    {% endif %}
                    {% endif %}


# TTS https://community.home-assistant.io/t/17track-integration/167602