binary_sensor:
  - platform: workday
    country: ZA
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]
    add_holidays:
      - '2021-12-25'

#timer:
#  88e9fe88abfe:
#    duration: '00:05:00'

input_datetime:
  88e9fe88abfe_off_time_1:
    name: 88e9fe88abfe off time 1
    has_date: false
    has_time: true
  88e9fe88abfe_on_time_1:
    name: 88e9fe88abfe off time 1
    has_date: false
    has_time: true
#  88e9fe88abfe_off_time_2:
#    name: 88e9fe88abfe off time 2
#    has_date: false
#    has_time: true
#  88e9fe88abfe_off_time_3:
#    name: 88e9fe88abfe off time 3
#    has_date: false
#    has_time: true

#input_number:
#  88e9fe88abfe_off_time_1:
#    name: 88e9fe88abfe off time slot 1
#    #initial: 4
#    min: 1
#    max: 60
#    step: 1
#  88e9fe88abfe_off_time_2:
#    name: 88e9fe88abfe off time slot 2
#    #initial: 4
#    min: 1
#    max: 60
#    step: 1
#  88e9fe88abfe_off_time_3:
#    name: 88e9fe88abfe off time slot 3
#    #initial: 4
#    min: 1
#    max: 60
#    step: 1

#automation:
#  # off based on input time
#  - alias: Turn off 88e9fe88abfe 1
#    trigger:
#      - platform: template
#        value_template: "{{ states('sensor.time') == (state_attr('input_datetime.88e9fe88abfe_off_time_1', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
#    condition:
#      - condition: state
#        entity_id: binary_sensor.workday_sensor
#        state: "on"
#    action:
#      - service: switch.turn_off
#        data:
#          entity_id: switch.88e9fe88abfe
#      - service: switch.turn_off
#        data:
#          entity_id: switch.office_feed_2
#
#    #- service: timer.start
#    #  data_template:
#    #    entity_id: timer.88e9fe88abfe
#    #    duration: >
#    #      {{ states('input_number.88e9fe88abfe_off_time_1') | int * 60 }} 
#
#  # on based on input time
#  - alias: Turn on 88e9fe88abfe 1
#    trigger:
#      platform: template
#      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.88e9fe88abfe_on_time_1', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
#    action:
#    - service: switch.turn_on
#      data:
#        entity_id: switch.88e9fe88abfe
#    - service: switch.turn_on
#      data:
#        entity_id: switch.office_feed_2

##################

#  - alias: Turn off 88e9fe88abfe 2
#    trigger:
#      platform: template
#      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.88e9fe88abfe_off_time_2', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
#    action:
#    - service: switch.turn_off
#      data:
#        entity_id: switch.88e9fe88abfe
#    - service: timer.start
#      data_template:
#        entity_id: timer.88e9fe88abfe
#        duration: >
#          {{ states('input_number.88e9fe88abfe_off_time_2') | int * 60 }} 

#  - alias: Turn off 88e9fe88abfe 3
#    trigger:
#      platform: template
#      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.88e9fe88abfe_off_time_3', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
#    action:
#    - service: switch.turn_off
#      data:
#        entity_id: switch.88e9fe88abfe
#    - service: timer.start
#      data_template:
#        entity_id: timer.88e9fe88abfe
#        duration: >
#          {{ states('input_number.88e9fe88abfe_off_time_3') | int * 60 }} 

  # start timer when turned off
#  - alias: Start timer after Turn off network access
#    trigger:
#      - platform: state
#        entity_id: switch.88e9fe88abfe
#        from: 'on'
#        to: 'off'
#    condition:
#      - condition: state
#        entity_id: input_boolean.homeassistant_recently_started
#        state: 'off'
#      - condition: state
#        entity_id: timer.88e9fe88abfe
#        state: 'idle'
#    action:
#    - service: timer.start
#      data_template:
#        entity_id: timer.88e9fe88abfe
#        duration: >
#          {{ states('input_number.88e9fe88abfe_off_time_1') | int * 60 }} 

  # 88e9fe88abfe on when timer finish
#  - alias: Turn on 88e9fe88abfe
#    trigger:
#      - platform: event
#        event_type: timer.finished
#        event_data:
#          entity_id: timer.88e9fe88abfe
#    action:
#      - service: switch.turn_on
#        data:
#          entity_id: switch.88e9fe88abfe