---
sensor:
  - platform: command_line
    name: 'Google Cache Redirector'
    command: "curl -s https://redirector.googlevideo.com/report_mapping?di=no"
    # value_template: '{{ value | multiply(1000) | round(0) }}' # Not sure if in cm or mm.
    scan_interval: 300

automation:
  - alias: "Google Cache Redirector Update"
    initial_state: 'on'
    trigger:
      - entity_id: sensor.google_cache_redirector
        platform: state
    action:
      - alias: "Alert change"
        service: script.alert
        data:
          icon: ':earth_africa:'
          object: 'Google Cache'
          target: 'alerts-david'
          message: >
            Redirect updated To: {{ states.sensor.google_cache_redirector.state }}
      - alias: "Alert change from"
        service: script.alert
        data:
          icon: ':earth_africa:'
          object: 'Google Cache'
          target: 'alerts-david'
          message: >
            Redirect updated From: {{ trigger.from_state }}
