# From: https://github.com/bieniu/ha-shellies-discovery
automation:
  - alias: '[Shellies] Initialize on Hass Started'
    initial_state: on
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: automation.trigger
        data:
          entity_id: automation.shellies_announce

  - id: shellies_announce
    alias: 'Shellies Announce'
    trigger:
      - platform: homeassistant
        event: start
      - platform: time_pattern
        hours: "/1"
    action:
      service: mqtt.publish
      data:
        topic: shellies/command
        payload: announce
  
  - id: 'shellies_discovery'
    alias: 'Shellies Discovery'
    mode: queued
    max: 999
    trigger:
      platform: mqtt
      topic: shellies/announce
    action:
      service: python_script.shellies_discovery
      data_template:
        id: '{{ trigger.payload_json.id }}'
        mac: '{{ trigger.payload_json.mac }}'
        fw_ver: '{{ trigger.payload_json.fw_ver }}'
        model: '{{ trigger.payload_json.model }}'
        mode: '{{ trigger.payload_json.mode | default }}'
        host: '{{ trigger.payload_json.ip }}'
        discovery_prefix: 'homeassistant'
        qos: 2
        # Dimmers
        shellydimmer-D3E771:
          light-0-name: "Lounge"
        shellydimmer-D42C70:
          light-0-name: "Kitchen"
        shellydimmer-D3EAC3:
          light-0-name: "Braai Room"
        shellydimmer2-40F52000229E:
          light-0-name: "Main Bedroom"
        shellydimmer2-40F520016DF0:
          light-0-name: "Small Bedroom"
        # Shelly1s as switch
        shelly1-98F4ABF32146:
          relay-0-name: "Water Sprayers"
        # Shelly1s as light
        shelly1-E097ED:
          relay-0: "light"
          relay-0-name: "Back Garage"
        shelly1-2472C6:
          relay-0: "light"
          relay-0-name: "Outside Kitchen"
        shelly1-E098068CCA22:
          relay-0: "light"
          relay-0-name: "Outside Back"
        shelly1-8CAAB5055B7E:
          relay-0: "light"
          relay-0-name: Front Garage
        shelly1-E098068CC938:
          relay-0: "light"
          relay-0-name: Braai
        shelly1-8CAAB505C111:
          relay-0: "light"
          relay-0-name: Braai Bathroom
        shelly1-8CAAB5056074:
          relay-0: "light"
          relay-0-name: Pool
        shelly1-8CAAB505CAFC:
          relay-0: "light"
          relay-0-name: Small Bathroom
        # Shelly1pms as switch
        shelly1pm-8CAAB505FD7D:
          relay-0-name: Pool pump
          expire_after: 7200
        # Shelly25
        shellyswitch25-40F520009D50:
          relay-0: "light"
          relay-0-name: "Outside Main Bathroom"
          relay-1: "light"
          relay-1-name: "Courtyard Main Bedroom"
        shellyswitch25-40F520008DBD:
          relay-0: "light"
          relay-0-name: "Outside Scullery"
          relay-1: "light"
          relay-1-name: "Scullery"
        shellyswitch25-40F520014D36:
          relay-0: "light"
          relay-0-name: "Front Door"
          relay-1: "light"
          relay-1-name: "Outside Porch"
        shellyswitch25-40F520007EC0:
          relay-0: "light"
          relay-0-name: "Courtyard Lounge"
          relay-1: "light"
          relay-1-name: "Dining"
          expire_after: 7200
        shellyswitch25-40F52000F5B7:
          relay-0: "light"
          relay-0-name: "Bar"
          relay-1: "light"
          relay-1-name: "Courtyard Braai"
        shellyswitch25-40F52000E5A4:
          relay-0: "light"
          relay-0-name: "Main Ensuite"
          relay-1: "light"
          relay-1-name: "Main Bathroom"
        shellyswitch25-40F520011E45:
          relay-0: "light"
          relay-0-name: "Hallway entry"
          relay-1: "light"
          relay-1-name: "Hallway"
        shellyswitch25-40F5200090ED:
          relay-0: "light"
          relay-0-name: "Front Hallway"
          relay-1: "light"
          relay-1-name: "Front Bathroom"