automation:
  # Kitchen button
  - alias: 'MQTT Zigbee Button Kitchen single click'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: 'tele/zigbee/0xF4D6/Click'
        payload: 'single'
    action:
      - service: light.toggle
        data:
          entity_id: light.kitchen
    #  - service: input_boolean.toggle
    #    data:
    #      entity_id: input_boolean.kitchenwork

  # Main Bathroom button
  - alias: 'MQTT Zigbee Button Main Bathroom single click'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: 'tele/zigbee/0x2839/Click'
        payload: 'single'
    action:
      - service: light.toggle
        data:
          entity_id: light.main_bathroom

  # Lounge button
  - alias: 'MQTT Zigbee Button Main Bathroom hold action'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: 'tele/zigbee/0x4C00/Action'
        payload: 'hold'
    action:
      - service: automation.trigger
        data:
          entity_id:
            - automation.set_lights_when_plex_kodi_is_playing
  - alias: 'MQTT Zigbee Button Main Bathroom single click'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: 'tele/zigbee/0x4C00/Click'
        payload: 'single'
    action:
      - service: light.turn_off
        data:
          entity_id:
            - light.lounge