---

automation:
  # Kitchen button
  - alias: 'MQTT Zigbee Button Kitchen single click'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: 'tele/zigbee/Kitchen Button/Click'
        payload: 'single'
    action:
      - service: light.toggle
        data:
          entity_id: light.kitchen
    #  - service: input_boolean.toggle
    #    data:
    #      entity_id: input_boolean.kitchenwork
  - alias: 'MQTT Zigbee Button Kitchen hold action'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: 'tele/zigbee/Kitchen Button/Action'
        payload: 'single'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.kitchen
          transition: 50
          brightness: >-
            {% set time = states('sensor.time') %}
            {%- if(is_state('input_boolean.kitchenwork','on')) -%}
            185
            {% elif '18:00' <= time <= '20:25' %}
            175
            {% elif '05:30' <= time <= '07:30' %}
            175
            {%- else -%}
            175
            {%- endif -%}

  # Main Bathroom button
  - alias: 'MQTT Zigbee Button Main Bathroom single click'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: 'tele/zigbee/Main Bathroom Button/Click'
        payload: 'single'
    condition:
      - condition: state
        entity_id: timer.main_bathroom
        state: 'idle'
    action:
      - service: automation.trigger
        data:
          skip_condition: true
          entity_id: automation.turn_on_main_bathroom_lights_fan

  - alias: 'MQTT Zigbee Button Main Bathroom single click'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: 'tele/zigbee/Main Bathroom Button/Click'
        payload: 'single'
    condition:
      - condition: state
        entity_id: timer.main_bathroom
        state: 'active'
    action:
      - service: timer.cancel
        data:
          entity_id: timer.main_bathroom
      - service: light.turn_off
        data:
          entity_id: light.main_bathroom

  # Lounge button
  - alias: 'MQTT Zigbee Button Lounge hold action'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: 'tele/zigbee/Lounge Button/Action'
        payload: 'hold'
    action:
      - service: automation.trigger
        data:
          entity_id:
            - automation.set_lights_when_plex_kodi_is_playing
  - alias: 'MQTT Zigbee Button Lounge single click'
    initial_state: true
    trigger:
      - platform: mqtt
        topic: 'tele/zigbee/Lounge Button/Click'
        payload: 'single'
    action:
      - service: light.turn_off
        data:
          entity_id:
            - light.lounge
